# Generated by Django 2.2.2 on 2020-01-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=40)),
                ('area_pincode', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=40)),
                ('c_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='p_package',
            fields=[
                ('p_pk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_pk_name', models.CharField(max_length=40)),
                ('p_pk_desc', models.CharField(max_length=200)),
                ('p_pk_amount', models.IntegerField(max_length=10)),
                ('p_pk_duration', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'p_package',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('contact', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('user_gender', models.CharField(max_length=7)),
                ('is_admin', models.IntegerField()),
                ('otp', models.CharField(max_length=10)),
                ('otp_used', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.Area')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='photographer',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=40)),
                ('p_contact', models.IntegerField(max_length=11)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_password', models.CharField(max_length=20, unique=True)),
                ('p_address', models.CharField(max_length=200)),
                ('p_gender', models.CharField(max_length=7)),
                ('p_desc', models.CharField(max_length=200)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.Area')),
                ('p_pk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.p_package')),
            ],
            options={
                'db_table': 'photographer',
            },
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('pk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pk_name', models.CharField(max_length=40)),
                ('pk_desc', models.CharField(max_length=200)),
                ('pk_amount', models.IntegerField(max_length=10)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.category')),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('g_id', models.IntegerField(primary_key=True, serialize=False)),
                ('g_path', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.category')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.photographer')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_date', models.DateTimeField()),
                ('f_desc', models.CharField(max_length=200)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.photographer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.Users')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_date', models.DateTimeField()),
                ('b_desc', models.CharField(max_length=200)),
                ('b_status', models.CharField(max_length=200)),
                ('b_amount', models.IntegerField(max_length=10)),
                ('payment_status', models.CharField(max_length=200)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.photographer')),
                ('pk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.package')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.Users')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.City'),
        ),
    ]
