# Generated by Django 2.2.2 on 2020-02-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('cn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cn_email', models.EmailField(max_length=254)),
                ('cn_phone', models.IntegerField(max_length=11)),
                ('cn_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
