# Generated by Django 2.2.2 on 2020-02-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0003_contactus_cn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
