# Generated by Django 2.2.2 on 2020-02-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0004_category_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='p_image',
            field=models.FileField(default=-1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image_path',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='g_path',
            field=models.FileField(upload_to=''),
        ),
    ]
