# Generated by Django 2.2.2 on 2020-02-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0005_auto_20200220_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='cn_phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
