# Generated by Django 2.2.2 on 2020-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0006_auto_20200222_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='b_date',
            field=models.DateField(),
        ),
    ]
