# Generated by Django 2.2.2 on 2020-04-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0007_auto_20200222_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='p_contact',
            field=models.IntegerField(),
        ),
    ]
