# Generated by Django 2.2.2 on 2020-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0008_auto_20200407_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='p_contact',
            field=models.IntegerField(max_length=11),
        ),
    ]
