# Generated by Django 2.2.2 on 2020-05-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0011_auto_20200425_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp_used',
            field=models.IntegerField(default=0),
        ),
    ]
