# Generated by Django 2.2.2 on 2020-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0012_auto_20200527_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='cn_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='p_contact',
            field=models.CharField(max_length=11),
        ),
    ]
