# Generated by Django 2.2.2 on 2020-05-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0013_auto_20200527_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_amt',
            field=models.IntegerField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
