# Generated by Django 2.2.2 on 2020-05-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0014_category_c_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='c_amt',
        ),
    ]
