# Generated by Django 2.2.2 on 2020-05-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0015_remove_category_c_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='p_amt',
            field=models.IntegerField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
