# Generated by Django 2.2.2 on 2020-05-30 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0017_auto_20200530_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ppp',
            fields=[
                ('ppp_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.category')),
            ],
            options={
                'db_table': 'ppp',
            },
        ),
    ]
