# Generated by Django 2.2.2 on 2020-05-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0018_ppp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ppp',
        ),
    ]
