# Generated by Django 2.2.2 on 2020-05-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0022_auto_20200530_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='c_id',
        ),
    ]
