# Generated by Django 2.2.2 on 2020-05-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0023_remove_photographer_c_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ppp',
        ),
    ]
