# Generated by Django 2.2.2 on 2020-05-30 10:11

import SJMS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0024_delete_ppp'),
    ]

    operations = [
        migrations.CreateModel(
            name='photographers',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=40)),
                ('p_image', models.FileField(upload_to='')),
                ('p_contact', models.CharField(max_length=11)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_password', models.CharField(max_length=20, unique=True)),
                ('p_address', models.CharField(max_length=200)),
                ('p_gender', models.CharField(max_length=7)),
                ('p_amt', models.IntegerField(max_length=10)),
                ('c_id', models.IntegerField(verbose_name=SJMS.models.category)),
                ('p_otp', models.CharField(max_length=10)),
                ('p_otp_used', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.Area')),
                ('p_pk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.p_package')),
            ],
            options={
                'db_table': 'photographers',
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.photographers'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.photographers'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SJMS.photographers'),
        ),
        migrations.DeleteModel(
            name='photographer',
        ),
    ]
