# Generated by Django 2.2.2 on 2020-05-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0026_auto_20200530_1602'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photographers',
            table='photographer',
        ),
    ]
