# Generated by Django 2.2.2 on 2020-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0027_auto_20200530_1606'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photographers',
            table='photographers',
        ),
    ]
