# Generated by Django 2.2.2 on 2020-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0029_auto_20200530_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographers',
            name='p_desc',
            field=models.CharField(default=-1, max_length=200),
            preserve_default=False,
        ),
    ]
