# Generated by Django 2.2.2 on 2020-05-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0031_photographers_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographers',
            name='c_id',
        ),
    ]
