# Generated by Django 2.2.2 on 2020-05-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0033_photographers_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographers',
            old_name='p_desc',
            new_name='p_descp',
        ),
    ]
