# Generated by Django 2.2.2 on 2020-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0035_auto_20200530_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
    ]
