# Generated by Django 2.2.2 on 2020-05-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SJMS', '0037_remove_photographers_c_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cat',
        ),
    ]
